# Generated by Django 5.2.1 on 2025-05-30 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_tracker', '0002_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='in_stock',
            new_name='stocked',
        ),
    ]
