# Generated by Django 5.2.1 on 2025-05-31 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_tracker', '0003_rename_in_stock_product_stocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
